### ISSUE TITLE
UI Wireframe

### ISSUE THREAD

**Issue by krissolui** [betterbettor/bet-better-react#2]
Single page UI

**Requirements**

Core Features:
- List all matches with overview stats (e.g. teams, fixtures, up-to-date odds)
- Expandable/collapsible match item with detailed stats (e.g. historical odds)

Secondary Features:
- Search/filter matches on the result page for a game or a team (`gameId`/`teamId`)
- Bookmark favourite games/teams (`gameId`/ `teamId`)

**Comment by wkip1220withweb** [comment]
https://www.figma.com/file/1FyQ6nWP8v4wJRaiLND7i0/betbetter-layout-draft?type=design&node-id=30%3A4&mode=design&t=ZU29gF97Unp0PXON-1
