### ISSUE TITLE
Replace Search Bar with Datepicker Filter

### ISSUE THREAD

**Issue by louvrecly** [betterbettor/bet-better-react#23]
Replace the search bar with a date picker Filter

**Comment by wkip1220withweb** [comment]
![date-picking@1x](https://github.com/betterbettor/bet-better-react/assets/146969486/64dc639c-aa51-4fed-ae90-2f322fbb87ad)
Is this wireframe layout too complicated to be developed, as it is the screenshot as when "Today" is clicked, the calender daypicker is shown.

**Comment by wkip1220withweb** [comment]
https://cloud.justinmind.com/usernote/prototype/409c2169e2352b1c7e098cf4eb60cdd28081fca44bed1e724fed0b369223f40f 

It will be keeping updated until it is finished.

**Comment by wkip1220withweb** [comment]
https://www.figma.com/file/1FyQ6nWP8v4wJRaiLND7i0/betbetter-wireframe?type=design&node-id=130%3A6&mode=design&t=zzQYuo7uMUgE0dzB-1
